winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Clipchamp.Clipchamp_yxz26nhyzhsrt
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.BingNews_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.BingWeather_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.GamingApp_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.GetHelp_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.Getstarted_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.People_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.WindowsMaps_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.Xbox.TCUI_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.XboxGameOverlay_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.XboxGamingOverlay_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements microsoft.windowscommunicationsapps_8wekyb3d8bbwe	
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.YourPhone_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.ZuneMusic_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements Microsoft.ZuneVideo_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements MicrosoftTeams_8wekyb3d8bbwe
winget uninstall --exact --silent --force --purge --disable-interactivity --accept-source-agreements SpotifyAB.SpotifyMusic_zpdnekdrzrea0
